### PR TITLE
Ensure update checks on platforms without auto-update support

### PR DESCRIPTION
**Pull request by xyloflake**
### Changes
1. **Variable Renaming for Clarity**:
   - `isAutoupdateAvailable` renamed to `isAutoupdateSupported`.
   - `isWithAutoupdate` renamed to `willAutoupdate`.
   - These changes enhance code readability and better convey the purpose of each variable.

2. **Improved Update Checking Logic**:
   - Use fallback mechanism to ensure updates are checked even when auto-updates are not supported or explicitly disabled.
   - This ensures that all platforms, regardless of their auto-update capabilities, will still perform update checks.

### CODE REVIEW

**Review by gamersi — DISMISSED** [review]
LGTM

**Comment by xyloflake** [comment]
@gamersi @staniel359 before merging this, please try building. For some unknown reason, electron-builder doesn't seem to generate the installers for me. Check for windows needed.

**Comment by staniel359** [comment]
@xyloflake Are you running `pnpm package:all`?

**Comment by xyloflake** [comment]
@staniel359 `pnpm build:all`

**Comment by staniel359** [comment]
@xyloflake This will just build, without the installers.
For installers run `pnpm package:all`

**Comment by xyloflake** [comment]
my bad, sorry

**Pull request closed without merging**
