### PR TITLE
Update italian language

### PR DESCRIPTION
**Pull request by filipporomani**
This translation is compared to the en.json file and should contain everything in the right place.

### CODE REVIEW

**Comment by staniel359** [comment]
@filipporomani Please run `git pull` and update your translations.
Seems like you used the old `en.json`.

**Comment by filipporomani** [comment]
I used the repo one, i edited it directly in GitHub.com

**Comment by staniel359** [comment]
@filipporomani Okay, I'll just add your translations manually.
1. Could you confirm that `actions` key contains all verbs?
2. And you've missed `about.contact` key.

**Comment by staniel359** [comment]
@filipporomani Okay, nevermind.
Thank you for your help.

**Pull request closed without merging**
