### PR TITLE
Add instructions

### PR DESCRIPTION
**Pull request by xyloflake**
Adds instructions for spotify integration

### CODE REVIEW

**Review by gamersi — DISMISSED** [review]
LGTM. Fix the small error I sent on discord and you are good to merge

**Comment by xyloflake** [comment]
Thanks @gamersi 
Please re-review

**Review by gamersi — APPROVED** [review]
LGTM

**Review by staniel359 — APPROVED** [review]
@xyloflake Let's merge it for now, as this can always be improved.

**Pull request merged**
