### PR TITLE
Add star history in README

### PR DESCRIPTION
**Pull request by xyloflake**

### CODE REVIEW

**Review by xyloflake — COMMENTED** [review]
LGTM

**Comment by staniel359** [comment]
@xyloflake The font. 😆

**Review by gamersi — APPROVED** [review]
LGTM

**Comment by xyloflake** [comment]
@staniel359 it's inevitable. The website doesn't allow any other font 🙂

I also hate it. But nothing to do :)

**Comment by staniel359** [comment]
@xyloflake Maybe there's another similar site?

**Comment by xyloflake** [comment]
@staniel359 tried finding one. There's no other option.

**Review by staniel359 — APPROVED** [review]

**Pull request merged**
