### PR TITLE
Update Copyright year

### PR DESCRIPTION
**Pull request by gamersi**
The copyright had 2023 and I updated it to 2024
really subtle and irrelevant change, i know

### CODE REVIEW

**Review by xyloflake — COMMENTED** [review]
LOL, I noticed that the day before yesterday but didn't seem to care. IMO, we should dynamically detect the current year and place it there, this ensures that copyright info doesn't change in different releases.

I'll wait for Staniel's review.

**Comment by gamersi** [comment]
> LOL, I noticed that the day before yesterday but didn't seem to care. IMO, we should dynamically detect the current year and place it there, this ensures that copyright info doesn't change in different releases.
> 
> I'll wait for Staniel's review.

yeah lets wait for his opinion, but that would make sense, i could implement it if staniel wants me to

**Comment by staniel359** [comment]
@gamersi Also [here](https://github.com/staniel359/muffon/blob/main/electron-builder.json) please.

**Comment by staniel359** [comment]
@xyloflake
> IMO, we should dynamically detect the current year

I think there's no need for that. It happens once a year.

**Review by xyloflake — APPROVED** [review]
LGTM

**Review by staniel359 — APPROVED** [review]
@gamersi @xyloflake Thanks guys!

**Pull request merged**
