### PR TITLE
Customize badges and fix github underline bug

### PR DESCRIPTION
**Pull request by xyloflake**
About why it has the compressed form, [have a look](https://stackoverflow.com/questions/77658005/a-blue-line-under-badges-in-readme-github-overview).

I had the same problem of underlines, removing ALL the whitespaces fix it :)

### CODE REVIEW

**Comment by xyloflake** [comment]
Please compare the readme of both the branches on Github’s website.

**Review by gamersi — DISMISSED** [review]
Good!
People with OCD will thank you

**Comment by xyloflake** [comment]
> Good!
> 
> People with OCD will thank you

ROFL 🤣

**Comment by xyloflake** [comment]
# TL; DR
The discord label was too long, a logo is sufficient to let people know that it’s discord.

**Review by staniel359 — APPROVED** [review]

**Review by gamersi — APPROVED** [review]
^ Wrong button (my last comment)

**Pull request merged**
