### PR TITLE
Documentation and Badge Update 🚀 

### PR DESCRIPTION
**Pull request by codeIntrovert**
## Pull Request: Documentation and Badge Update 🚀

Hey Team Muffon! 👋

I hope you're all doing well! I've made a small contribution to enhance the documentation and provide a live status of the last commit through badges. Here's a breakdown of the changes:

### Changes Made:
1. Added `<a> </a>` to the download count badge in `README.md` for improved documentation.
2. Introduced a new badge for the last commit to provide a live status of the repo's last update.

These updates aim to enhance the visual appeal and usability of the repository.

### Why this PR?

- **Documentation Improvement:** Added missing `<a> </a>` tags for consistency.
- **Live Status Badge:** Now you can quickly check when the repository was last updated.

### Future Collaboration:
I'm really excited about the project and would love to contribute more in the future. I'm open to feedback and happy to work collaboratively with Team Muffon. Let me know how I can further assist!

Looking forward to your feedback and the opportunity to contribute more to this awesome project! 🎉

Best regards,
codeIntrovert

### CODE REVIEW

**Review by gamersi — APPROVED** [review]
LGTM

**Review by xyloflake — APPROVED** [review]
Hey @codeIntrovert! Thank you for the small yet valuable PR. You can contribute by translating or if there's something you'd like to discuss about, join the [discord server](https://discord.gg/NzNm6b4prH).

Although not **very necessary**, but wouldn't hurt to add. Shows that the repo is actively maintained.

LGTM!

**Comment by xyloflake** [comment]
Will merge after @staniel359 reviews :)

**Comment by staniel359** [comment]
@codeIntrovert Thanks!

**Pull request merged**
