### PR TITLE
update dependencies & repatch electron-updater

### PR DESCRIPTION
**Pull request by xyloflake**

### CODE REVIEW

**Comment by xyloflake** [comment]
I've opened an issue in electron-builder regarding the "Could not find Visual Studio installation" error in v25 [here](https://github.com/electron-userland/electron-builder/issues/8580). Will repatch app-builder-lib once that's resolved.

**Comment by staniel359** [comment]
@xyloflake Sorry, can't accept it.
You should update only those deps that you patched.
Because some of the deps have breaking changes and may not work.

**Comment by gamersi** [comment]
> @xyloflake Sorry, can't accept it. You should update only those deps that you patched. Because some of the deps have breaking changes and may not work.

All the updates he made are minor or patch version bumps. I would test it and if it works, just update it. You can downgrade at any time either way.

**Comment by staniel359** [comment]
@gamersi Right. I'm just blind as always.

**Review by staniel359 — APPROVED** [review]

**Review by gamersi — APPROVED** [review]

**Pull request merged**
