### PR TITLE
Add Japanese language

### PR DESCRIPTION
**Pull request by maboroshin**
I'm on my way, can you make it to 1.5.0?
It is easier translation for me to merge once. Untranslated parts can be visualized

### CODE REVIEW

**Comment by staniel359** [comment]
@maboroshin Hello.
Thank you for contributing!

But there're many untranslated parts. Are you still working on them?

**Comment by maboroshin** [comment]
@staniel359  About half of it is done by translating. I can work faster after merging because I can visualize the unworked parts.

Progress was slow because it could not be visualized.

**Comment by staniel359** [comment]
@maboroshin By "merge" you mean releasing the next version?

**Comment by maboroshin** [comment]
@staniel359 I do not know which part was translated. So the translation was slow. It would be useful if a merged and Japanese version 1.5.0 is released.

More than 80-90% of the text have been translated, except for the "History - Activity".

**Pull request closed without merging**
