### PR TITLE
Windows Installer Size and Speed Optimization

### PR DESCRIPTION
**Pull request by xyloflake**
# Overview
This pull request addresses optimizations to [app-builder-lib](https://github.com/electron-userland/electron-builder/tree/master/packages/app-builder-lib), a pivotal component within the [electron-builder](https://github.com/electron-userland/electron-builder) monorepo.

# Enhancements
- Specifically tailored for version `24.13.3` of app-builder-lib, this patch introduces a novel **custom compression level** dubbed `ultra`. On platforms other than Windows, `ultra` is internally set to `maximum`. Conversely, on Windows, a bespoke high-compression algorithm has been utilized to optimize the size efficiency of the NSIS target. This measure was necessitated by issues encountered on non-Windows platforms, as evidenced by the [failed build](https://github.com/xyloflake/muffon/actions/runs/8927069728).

- Electron builder [internally resets the compression configuration option to `normal`](https://github.com/electron-userland/electron-builder/blob/b43490a274722aba398594bcf0156d1b3687e0d2/packages/app-builder-lib/src/targets/differentialUpdateInfoBuilder.ts#L61) for Windows, albeit without explicit rationale. Consequently, this patch intervenes to prevent the reset to `normal` exclusively for Windows systems, as the aforementioned algorithm cannot operate optimally on other platforms.

# Impact
- The adoption of `maximum` compression for `ultra` on macOS and Linux results in increased build times across all platforms. On Windows, there's a notable build time surge owing to the necessity to compile internal libraries post-patch, utilizing Visual Studio.

- Overall, this enhancement culminates in a `7MB` reduction in size.

- However, it's important to note an **8% slowdown in installation speed**, attributed to the heightened complexity of decompression.

# Build Checks
For reference, the latest build checks can be viewed [here](https://github.com/xyloflake/muffon/actions/runs/8927536421).
Build Status: Passing ✅

### CODE REVIEW

**Review by gamersi — APPROVED** [review]
LGTM

**Comment by staniel359** [comment]
@xyloflake Thanks for detailed description.
Have you considered contributing directly to electron-builder?
Or is it specifically for muffon?

**Comment by xyloflake** [comment]
It is specifically for muffon @staniel359 

I did consider contributing directly to electron builder but I realised that they reset the compression config from literally anything to normal. Now I've only tested for Windows and have no idea about how it behaves on non-Windows platforms. 

But I ran a CI build that failed (linked in the PR description), which tells me that it has problems on other platforms, therefore I had to apply the patch only for windows. 

Also the reset is done with a goofy comment above it, which makes me doubt if they'd like to change.

Moreover the v25 alphas are broken, I and @gamersi have tried building electron-builder from main but windows throws a fatal node-gyp error `VS installation not found`. Also their CI builds fail as well at macos tests (check electron builder repo github actions).

Once it becomes stable, I'll try to contribute directly to electron-builder although I am 90% sure they'll straight up reject the PR.

But let's hope for the best I guess.

For now, this is the solution to reducing `7MB` which may not sound like a big deal but it was quite complex to achieve such a feat.

Thanks.

**Comment by staniel359** [comment]
@xyloflake Got it.
Thank you for your work!

**Review by staniel359 — APPROVED** [review]

**Pull request merged**
