### PR TITLE
Fix set environment variable cross-platform

### LINKED ISSUE #35: `start:electron` script does not work on Windows
Executing `start:electron` will throw an error:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Borewit\code\github\muffon> yarn run start:electron
yarn run v1.22.10
$ NODE_ENV=development electron .
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Borewit\code\github\muffon>
```

As https://github.com/staniel359/muffon/blob/6f23daca6054428a4dc7b5a2613fce520c8198a9/package.json#L20
contains Unix specific environment variable assignment.

### PR DESCRIPTION
**Pull request by Borewit**
Fix `electron-start` script for Windows

Resolves #35

### CODE REVIEW

**Comment by staniel359** [comment]
@Borewit Why should it be done? The app is intended to be run packaged.

**Comment by Borewit** [comment]
> @Borewit Why should it be done? The app is intended to be run packaged.

Not at development time I suppose.
Maybe I am following the wrong procedure, but I am using Windows to start it, running:
- yarn run start
- yarn run start:electron

which seems to start the application, but it required this change.

**Comment by staniel359** [comment]
@Borewit That's right, but I don't think this should be a pull request.

**Comment by Borewit** [comment]
> @Borewit That's right, but I don't think this should be a pull request.

So how do I execute the second process (`yarn run start:electron`) in Windows?

**Comment by staniel359** [comment]
@Borewit Just open second Command Line/Terminal window.

**Comment by Borewit** [comment]
> @Borewit Just open second Command Line/Terminal window.

I understand that it has to be a different console, but `yarn run start:electron` does not work in Windows my friend, hence this PR. 

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Borewit\code\github\muffon> yarn run start:electron
yarn run v1.22.10
$ NODE_ENV=development electron .
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Borewit\code\github\muffon>
```

**Comment by staniel359** [comment]
@Borewit Then you need `cross-env`.
What I meant is your changes are shoud be just for your local environment and not a pull request.

**Comment by Borewit** [comment]
> your changes are should be just for your local environment

Why should I keep that fix just for myself?

**Comment by staniel359** [comment]
@Borewit Okay, fine. I'll merge this PR in case somebody else on Windows would like to run the app in development.

**Comment by Borewit** [comment]
I am getting lot's of CORS errors, should set some more relaxed policies somewhere?

**Comment by staniel359** [comment]
@Borewit In Chrome DevTools go to `Settings` and set a mark on `Selected context only`.

**Comment by Borewit** [comment]
> `Settings` and set a mark on `Selected context only`.

Got it, ⚙ (_Settings_) → _Preferences_ → _Console_ → ☑ _Selected context only_

**Pull request merged**
