### PR TITLE
Fix autoupdate beta message bug on Windows

### PR DESCRIPTION
**Pull request by staniel359**

### CODE REVIEW

**Comment by xyloflake** [comment]
Works @staniel359, but you should put conditional as `isAutoupdateBeta && isLinux` for better code quality since the message is only for Linux.

**Comment by xyloflake** [comment]
@staniel359 just remembered that we previously decided to keep the Windows build as beta due to lack of UI. Can you please revert `isAutoupdateBeta` to `true` and show the warning based on `isLinux && isAutoupdateBeta`?

**Review by xyloflake — CHANGES_REQUESTED** [review]
Please address the beforementioned concern(s).

**Comment by staniel359** [comment]
@xyloflake Done.

**Review by xyloflake — APPROVED** [review]
Thank you, LGTM!

**Review by gamersi — APPROVED** [review]
LGTM

**Pull request merged**
