### PR TITLE
fix audio

### PR DESCRIPTION
**Pull request by DoYouNotice**
fixed audio by adding try-supported-channel-layouts

### CODE REVIEW

**Comment by staniel359** [comment]
@DoYouNotice Have you tested it? Is it working?

**Comment by DoYouNotice** [comment]
@staniel359 yes worked for me fine.

**Comment by staniel359** [comment]
@DoYouNotice Good.
Would you mind if I close your PR and update my existing commit instead?

**Comment by DoYouNotice** [comment]
@staniel359 yea Sure No problem

**Comment by staniel359** [comment]
@DoYouNotice Okay, thanks for your help!

**Pull request closed without merging**
